<?php

namespace Models\Lists;

use Bitrix\Main\Entity\ReferenceField;
use Models\AbstractIblockPropertyValuesTable;

class DoctorsPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 16;

    public static function getMap(): array
    {
        $map = [];

        return parent::getMap() + $map; // TODO: Change the autogenerated stub

    }
}
